steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/okoa-sem-backend:$SHORT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/okoa-sem-backend:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'okoa-sem-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/okoa-sem-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--cpu-boost'
      - '--execution-environment'
      - 'gen2'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/okoa-sem-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY